### ISSUE TITLE
Missing .env.example in no-sentry branch

### ISSUE THREAD

**Issue by josem7** [nikolovlazar/flashcards#9]
I think you accidentally deleted the .example.env file from the no-sentry branch :)

I found it in the commit history, it's a very minor detail

```
DATABASE_URL="YOUR_DATABASE_URL"
SENTRY_DSN="YOUR_SENTRY_DSN"
NEXT_PUBLIC_SENTRY_DSN="YOUR_SENTRY_DSN"
NEXTAUTH_SECRET="YOUR_NEXTAUTH_SECRET"
```

**Comment by nikolovlazar** [comment]
Hey @josem7 thanks for opening this issue. I'm doing some refactoring on this repo right now, so the `no-sentry` branch is outdated right now. `main` is the one you should use. This issue is a reminder for me to clean up the branches 😁

In the mean time, I'm working on a more complex setup, with Go as backend and PostgreSQL as a database on this branch: https://github.com/nikolovlazar/flashcards/tree/go-postgresql-backend. Since I've created this repo for a workshop to demonstrate Sentry features (especially tracing), having two separate technologies is both very realistic as a real-world scenario and also much better for demonstrating distributed tracing.

**Comment by josem7** [comment]
Just FYI the no-sentry branch and YT tutorial helped me a lot. 

We are working on a solution that uses Sentry data and one of our users had a NextJs app (I've never worked with NextJs before). This tutorial helped me quickly create a demo NextJs app and link it to my Sentry to understand how Sentry captures the errors in Next and how to help our users correctly set up Sentry on their NextJs projects.
